resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: registry.ci.openshift.org/origin/multiarch-manager-operator
  newTag: v0.0.1
commonAnnotations:
  multiarch.openshift.io/image: registry.ci.openshift.org/origin/multiarch-manager-operator:v0.0.1
